//
//  RecipeModel.swift
//  recipeat
//
//  Created by Sina Haghighi on 2023-01-08.
//

import Foundation

enum Category: String{
    case dinner = "Dinner"
    case lunch = "Lunch"
    case breakfast = "Breakfast"
    case dessert = "Dessert"
    case drink = "Beverage"
    case alcBev = "Alcholic Beverage"
}

enum Cuisine: String{
    case chinese = "Chinese"
    case japanese = "Japanese"
    case american = "American"
    case italian = "Italian"
    case greek = "Greek"
    case indian = "Indian"
    case african = "African"
    case middle_eastern = "Middle Eastern"
    case french = "French"
    case spanish = "Spanish"
    case english = "English"
    case mexican = "Mexican"
    case southamerican = "South American"
    case easterneuropean = "Eastern European"
}

struct Recipe: Identifiable{
    let id = UUID()
    let name: String
    let image: String
    let description: String
    let ingredients: String
    let directions: String
    let category: Category.RawValue
    let cuisine: Cuisine.RawValue
    let datePublished: String
    let url: String
}


extension Recipe{
    static let all: [Recipe] = [
        Recipe(name: "Chicken Souvlaki",
               image: "https://www.mygreekdish.com/wp-content/uploads/2013/05/Greek-Chicken-Souvlaki-Skewers-recipe-5-1536x1111.jpg",
               description: "This Greek Chicken souvlaki recipe (skewers) takes you back to your favourite Taverna! Complete with best chicken souvlaki marinade and what to serve along.",
               ingredients: "4 boneless chicken breasts (approx. 1 kg/35 ounces),4 tbsps olive oil,juice of 1 lemon,1 clove of garlic, minced,2 tbsp dried oregano,salt and freshly ground pepper,1 cucumber,2 cloves of garlic, minced,1/4 of a cup extra virgin olive oil,500g of strained yogurt (18 ounces),1–2 tbsps of red wine vinegar,a pinch of salt,8 pita breads,olive oil,1–2 tsps dried oregano,1 tomato sliced,1 red onion sliced,fried potatoes (optional),romaine (cos) lettuce (optional),salt and freshly ground pepper,8–9 wooden skewers",
               directions: "To prepare this chicken souvlaki recipe, start by preparing the marinade. Cut the chicken breasts into 2-3 cm pieces and place them in a large bowl, along with all the marinade ingredients. Use your hands to mix really well, cover with plastic wrap and put in the fridge for 30-60 minutes. In the meantime prepare the tzatziki sauce for the chicken souvlaki. Pour in a blender the olive oil and grated garlic and blend until combined. Remove the skin and the seeds of the cucumber and grate it into a large bowl. Season with salt and pepper and leave aside for 10 minutes. Wrap the grated cucumber in a towel and squeeze, in order to get rid of the excess water. In a bowl, add the cucumber, the blended garlic and oil, the yogurt, 1-2 tbsps of red wine vinegar, a pinch of salt and blend, until the ingredients are combined. Store the tzatziki sauce in the fridge and always serve cold. To assemble the chicken souvlaki (skewers), cut the wooden skewers to fit your griddle pan and soak them in water. (This will prevent them from burning.) Thread the chicken pieces, comfortably, on the skewers. Preheat a grill or griddle pan on a high heat. Cook the chicken souvlaki (skewers) for about 8 to 10 minutes, turning occasionally, until nicely coloured on all sides and cooked through. While your chicken souvlaki is cooking, prepare the pita breads. Preheat the oven to 250C. Use a cooking brush to oil the pita breads on both sides and season with salt and oregano. Place a large oven tray (upside down) at the bottom of the oven and place the pita breads on top of the tray. Bake for 2 minutes. (Alternatively you can use a griddle pan or a grill.) To serve the chicken souvlaki (skewers), slice 2 red onions and place on a platter; top with the chicken souvlaki (skewers), drizzle with some extra virgin olive oil and a good squeeze of lemon juice. Serve while still warm with some pita breads and tzatziki sauce. You can also serve the chicken souvlaki (skewers) wrapped, like a sandwich. Spread some tzatziki sauce on the pita breads and top it with the chicken souvlaki (skewers), sliced onions, tomatoes and fried potatoes and wrap. Enjoy!",
               category: "Dinner",
               cuisine: "Greek",
               datePublished: "2014-05-26",
               url: "https://www.mygreekdish.com/recipe/souvlaki-with-chicken-and-pita-breads/"),
        Recipe(name: "Pho",
                image: "https://tastesbetterfromscratch.com/wp-content/uploads/2020/04/Pho-15.jpg",
                description: "This Greek Chicken souvlaki recipe (skewers) takes you back to your favourite Taverna! Complete with best chicken souvlaki marinade and what to serve along.",
                ingredients: "4 boneless chicken breasts (approx. 1 kg/35 ounces),4 tbsps olive oil,juice of 1 lemon,1 clove of garlic, minced,2 tbsp dried oregano,salt and freshly ground pepper,1 cucumber,2 cloves of garlic, minced,1/4 of a cup extra virgin olive oil,500g of strained yogurt (18 ounces),1–2 tbsps of red wine vinegar,a pinch of salt,8 pita breads,olive oil,1–2 tsps dried oregano,1 tomato sliced,1 red onion sliced,fried potatoes (optional),romaine (cos) lettuce (optional),salt and freshly ground pepper,8–9 wooden skewers",
                directions: "To prepare this chicken souvlaki recipe, start by preparing the marinade. Cut the chicken breasts into 2-3 cm pieces and place them in a large bowl, along with all the marinade ingredients. Use your hands to mix really well, cover with plastic wrap and put in the fridge for 30-60 minutes. In the meantime prepare the tzatziki sauce for the chicken souvlaki. Pour in a blender the olive oil and grated garlic and blend until combined. Remove the skin and the seeds of the cucumber and grate it into a large bowl. Season with salt and pepper and leave aside for 10 minutes. Wrap the grated cucumber in a towel and squeeze, in order to get rid of the excess water. In a bowl, add the cucumber, the blended garlic and oil, the yogurt, 1-2 tbsps of red wine vinegar, a pinch of salt and blend, until the ingredients are combined. Store the tzatziki sauce in the fridge and always serve cold. To assemble the chicken souvlaki (skewers), cut the wooden skewers to fit your griddle pan and soak them in water. (This will prevent them from burning.) Thread the chicken pieces, comfortably, on the skewers. Preheat a grill or griddle pan on a high heat. Cook the chicken souvlaki (skewers) for about 8 to 10 minutes, turning occasionally, until nicely coloured on all sides and cooked through. While your chicken souvlaki is cooking, prepare the pita breads. Preheat the oven to 250C. Use a cooking brush to oil the pita breads on both sides and season with salt and oregano. Place a large oven tray (upside down) at the bottom of the oven and place the pita breads on top of the tray. Bake for 2 minutes. (Alternatively you can use a griddle pan or a grill.) To serve the chicken souvlaki (skewers), slice 2 red onions and place on a platter; top with the chicken souvlaki (skewers), drizzle with some extra virgin olive oil and a good squeeze of lemon juice. Serve while still warm with some pita breads and tzatziki sauce. You can also serve the chicken souvlaki (skewers) wrapped, like a sandwich. Spread some tzatziki sauce on the pita breads and top it with the chicken souvlaki (skewers), sliced onions, tomatoes and fried potatoes and wrap. Enjoy!",
                category: "Dinner",
                cuisine: "Greek",
                datePublished: "2014-05-26",
                url: "https://www.mygreekdish.com/recipe/souvlaki-with-chicken-and-pita-breads/"),
        Recipe(name: "Chicken Pad Thai",
               image: "https://tastesbetterfromscratch.com/wp-content/uploads/2018/08/Pad-Thai-Web-7-1024x1536.jpg",
               description: "This Greek Chicken souvlaki recipe (skewers) takes you back to your favourite Taverna! Complete with best chicken souvlaki marinade and what to serve along.",
               ingredients: "4 boneless chicken breasts (approx. 1 kg/35 ounces),4 tbsps olive oil,juice of 1 lemon,1 clove of garlic, minced,2 tbsp dried oregano,salt and freshly ground pepper,1 cucumber,2 cloves of garlic, minced,1/4 of a cup extra virgin olive oil,500g of strained yogurt (18 ounces),1–2 tbsps of red wine vinegar,a pinch of salt,8 pita breads,olive oil,1–2 tsps dried oregano,1 tomato sliced,1 red onion sliced,fried potatoes (optional),romaine (cos) lettuce (optional),salt and freshly ground pepper,8–9 wooden skewers",
               directions: "To prepare this chicken souvlaki recipe, start by preparing the marinade. Cut the chicken breasts into 2-3 cm pieces and place them in a large bowl, along with all the marinade ingredients. Use your hands to mix really well, cover with plastic wrap and put in the fridge for 30-60 minutes. In the meantime prepare the tzatziki sauce for the chicken souvlaki. Pour in a blender the olive oil and grated garlic and blend until combined. Remove the skin and the seeds of the cucumber and grate it into a large bowl. Season with salt and pepper and leave aside for 10 minutes. Wrap the grated cucumber in a towel and squeeze, in order to get rid of the excess water. In a bowl, add the cucumber, the blended garlic and oil, the yogurt, 1-2 tbsps of red wine vinegar, a pinch of salt and blend, until the ingredients are combined. Store the tzatziki sauce in the fridge and always serve cold. To assemble the chicken souvlaki (skewers), cut the wooden skewers to fit your griddle pan and soak them in water. (This will prevent them from burning.) Thread the chicken pieces, comfortably, on the skewers. Preheat a grill or griddle pan on a high heat. Cook the chicken souvlaki (skewers) for about 8 to 10 minutes, turning occasionally, until nicely coloured on all sides and cooked through. While your chicken souvlaki is cooking, prepare the pita breads. Preheat the oven to 250C. Use a cooking brush to oil the pita breads on both sides and season with salt and oregano. Place a large oven tray (upside down) at the bottom of the oven and place the pita breads on top of the tray. Bake for 2 minutes. (Alternatively you can use a griddle pan or a grill.) To serve the chicken souvlaki (skewers), slice 2 red onions and place on a platter; top with the chicken souvlaki (skewers), drizzle with some extra virgin olive oil and a good squeeze of lemon juice. Serve while still warm with some pita breads and tzatziki sauce. You can also serve the chicken souvlaki (skewers) wrapped, like a sandwich. Spread some tzatziki sauce on the pita breads and top it with the chicken souvlaki (skewers), sliced onions, tomatoes and fried potatoes and wrap. Enjoy!",
               category: "Dinner",
               cuisine: "Greek",
               datePublished: "2014-05-26",
               url: "https://www.mygreekdish.com/recipe/souvlaki-with-chicken-and-pita-breads/"),
        Recipe(name: "Penne Alla Vodka",
               image: "https://assets.bonappetit.com/photos/5a8da4996497380283798c16/1:1/w_2240,c_limit/rigatoni-with-vodka-sauce.jpg",
               description: "This Greek Chicken souvlaki recipe (skewers) takes you back to your favourite Taverna! Complete with best chicken souvlaki marinade and what to serve along.",
               ingredients: "4 boneless chicken breasts (approx. 1 kg/35 ounces),4 tbsps olive oil,juice of 1 lemon,1 clove of garlic, minced,2 tbsp dried oregano,salt and freshly ground pepper,1 cucumber,2 cloves of garlic, minced,1/4 of a cup extra virgin olive oil,500g of strained yogurt (18 ounces),1–2 tbsps of red wine vinegar,a pinch of salt,8 pita breads,olive oil,1–2 tsps dried oregano,1 tomato sliced,1 red onion sliced,fried potatoes (optional),romaine (cos) lettuce (optional),salt and freshly ground pepper,8–9 wooden skewers",
               directions: "To prepare this chicken souvlaki recipe, start by preparing the marinade. Cut the chicken breasts into 2-3 cm pieces and place them in a large bowl, along with all the marinade ingredients. Use your hands to mix really well, cover with plastic wrap and put in the fridge for 30-60 minutes. In the meantime prepare the tzatziki sauce for the chicken souvlaki. Pour in a blender the olive oil and grated garlic and blend until combined. Remove the skin and the seeds of the cucumber and grate it into a large bowl. Season with salt and pepper and leave aside for 10 minutes. Wrap the grated cucumber in a towel and squeeze, in order to get rid of the excess water. In a bowl, add the cucumber, the blended garlic and oil, the yogurt, 1-2 tbsps of red wine vinegar, a pinch of salt and blend, until the ingredients are combined. Store the tzatziki sauce in the fridge and always serve cold. To assemble the chicken souvlaki (skewers), cut the wooden skewers to fit your griddle pan and soak them in water. (This will prevent them from burning.) Thread the chicken pieces, comfortably, on the skewers. Preheat a grill or griddle pan on a high heat. Cook the chicken souvlaki (skewers) for about 8 to 10 minutes, turning occasionally, until nicely coloured on all sides and cooked through. While your chicken souvlaki is cooking, prepare the pita breads. Preheat the oven to 250C. Use a cooking brush to oil the pita breads on both sides and season with salt and oregano. Place a large oven tray (upside down) at the bottom of the oven and place the pita breads on top of the tray. Bake for 2 minutes. (Alternatively you can use a griddle pan or a grill.) To serve the chicken souvlaki (skewers), slice 2 red onions and place on a platter; top with the chicken souvlaki (skewers), drizzle with some extra virgin olive oil and a good squeeze of lemon juice. Serve while still warm with some pita breads and tzatziki sauce. You can also serve the chicken souvlaki (skewers) wrapped, like a sandwich. Spread some tzatziki sauce on the pita breads and top it with the chicken souvlaki (skewers), sliced onions, tomatoes and fried potatoes and wrap. Enjoy!",
               category: "Dinner",
               cuisine: "Greek",
               datePublished: "2014-05-26",
               url: "https://www.mygreekdish.com/recipe/souvlaki-with-chicken-and-pita-breads/"),
        Recipe(name: "Margarita Pizza",
               image: "https://ciaoflorentina.com/wp-content/uploads/2011/01/Rustic-Pizza-Dough-11.jpg",
               description: "This Greek Chicken souvlaki recipe (skewers) takes you back to your favourite Taverna! Complete with best chicken souvlaki marinade and what to serve along.",
               ingredients: "4 boneless chicken breasts (approx. 1 kg/35 ounces),4 tbsps olive oil,juice of 1 lemon,1 clove of garlic, minced,2 tbsp dried oregano,salt and freshly ground pepper,1 cucumber,2 cloves of garlic, minced,1/4 of a cup extra virgin olive oil,500g of strained yogurt (18 ounces),1–2 tbsps of red wine vinegar,a pinch of salt,8 pita breads,olive oil,1–2 tsps dried oregano,1 tomato sliced,1 red onion sliced,fried potatoes (optional),romaine (cos) lettuce (optional),salt and freshly ground pepper,8–9 wooden skewers",
               directions: "To prepare this chicken souvlaki recipe, start by preparing the marinade. Cut the chicken breasts into 2-3 cm pieces and place them in a large bowl, along with all the marinade ingredients. Use your hands to mix really well, cover with plastic wrap and put in the fridge for 30-60 minutes. In the meantime prepare the tzatziki sauce for the chicken souvlaki. Pour in a blender the olive oil and grated garlic and blend until combined. Remove the skin and the seeds of the cucumber and grate it into a large bowl. Season with salt and pepper and leave aside for 10 minutes. Wrap the grated cucumber in a towel and squeeze, in order to get rid of the excess water. In a bowl, add the cucumber, the blended garlic and oil, the yogurt, 1-2 tbsps of red wine vinegar, a pinch of salt and blend, until the ingredients are combined. Store the tzatziki sauce in the fridge and always serve cold. To assemble the chicken souvlaki (skewers), cut the wooden skewers to fit your griddle pan and soak them in water. (This will prevent them from burning.) Thread the chicken pieces, comfortably, on the skewers. Preheat a grill or griddle pan on a high heat. Cook the chicken souvlaki (skewers) for about 8 to 10 minutes, turning occasionally, until nicely coloured on all sides and cooked through. While your chicken souvlaki is cooking, prepare the pita breads. Preheat the oven to 250C. Use a cooking brush to oil the pita breads on both sides and season with salt and oregano. Place a large oven tray (upside down) at the bottom of the oven and place the pita breads on top of the tray. Bake for 2 minutes. (Alternatively you can use a griddle pan or a grill.) To serve the chicken souvlaki (skewers), slice 2 red onions and place on a platter; top with the chicken souvlaki (skewers), drizzle with some extra virgin olive oil and a good squeeze of lemon juice. Serve while still warm with some pita breads and tzatziki sauce. You can also serve the chicken souvlaki (skewers) wrapped, like a sandwich. Spread some tzatziki sauce on the pita breads and top it with the chicken souvlaki (skewers), sliced onions, tomatoes and fried potatoes and wrap. Enjoy!",
               category: "Dinner",
               cuisine: "Greek",
               datePublished: "2014-05-26",
               url: "https://www.mygreekdish.com/recipe/souvlaki-with-chicken-and-pita-breads/"),
        Recipe(name: "Beer Battered Fish and Chips",
               image: "https://www.thespruceeats.com/thmb/k8Ejnb3LR7yrhwGirJEC2x6r1sg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/best-fish-and-chips-recipe-434856-Hero-5b61b89346e0fb00500f2141.jpg",
               description: "This Greek Chicken souvlaki recipe (skewers) takes you back to your favourite Taverna! Complete with best chicken souvlaki marinade and what to serve along.",
               ingredients: "4 boneless chicken breasts (approx. 1 kg/35 ounces),4 tbsps olive oil,juice of 1 lemon,1 clove of garlic, minced,2 tbsp dried oregano,salt and freshly ground pepper,1 cucumber,2 cloves of garlic, minced,1/4 of a cup extra virgin olive oil,500g of strained yogurt (18 ounces),1–2 tbsps of red wine vinegar,a pinch of salt,8 pita breads,olive oil,1–2 tsps dried oregano,1 tomato sliced,1 red onion sliced,fried potatoes (optional),romaine (cos) lettuce (optional),salt and freshly ground pepper,8–9 wooden skewers",
               directions: "To prepare this chicken souvlaki recipe, start by preparing the marinade. Cut the chicken breasts into 2-3 cm pieces and place them in a large bowl, along with all the marinade ingredients. Use your hands to mix really well, cover with plastic wrap and put in the fridge for 30-60 minutes. In the meantime prepare the tzatziki sauce for the chicken souvlaki. Pour in a blender the olive oil and grated garlic and blend until combined. Remove the skin and the seeds of the cucumber and grate it into a large bowl. Season with salt and pepper and leave aside for 10 minutes. Wrap the grated cucumber in a towel and squeeze, in order to get rid of the excess water. In a bowl, add the cucumber, the blended garlic and oil, the yogurt, 1-2 tbsps of red wine vinegar, a pinch of salt and blend, until the ingredients are combined. Store the tzatziki sauce in the fridge and always serve cold. To assemble the chicken souvlaki (skewers), cut the wooden skewers to fit your griddle pan and soak them in water. (This will prevent them from burning.) Thread the chicken pieces, comfortably, on the skewers. Preheat a grill or griddle pan on a high heat. Cook the chicken souvlaki (skewers) for about 8 to 10 minutes, turning occasionally, until nicely coloured on all sides and cooked through. While your chicken souvlaki is cooking, prepare the pita breads. Preheat the oven to 250C. Use a cooking brush to oil the pita breads on both sides and season with salt and oregano. Place a large oven tray (upside down) at the bottom of the oven and place the pita breads on top of the tray. Bake for 2 minutes. (Alternatively you can use a griddle pan or a grill.) To serve the chicken souvlaki (skewers), slice 2 red onions and place on a platter; top with the chicken souvlaki (skewers), drizzle with some extra virgin olive oil and a good squeeze of lemon juice. Serve while still warm with some pita breads and tzatziki sauce. You can also serve the chicken souvlaki (skewers) wrapped, like a sandwich. Spread some tzatziki sauce on the pita breads and top it with the chicken souvlaki (skewers), sliced onions, tomatoes and fried potatoes and wrap. Enjoy!",
               category: "Dinner",
               cuisine: "Greek",
               datePublished: "2014-05-26",
               url: "https://www.mygreekdish.com/recipe/souvlaki-with-chicken-and-pita-breads/"),
        Recipe(name: "Beef Souvlaki",
               image: "https://www.lecremedelacrumb.com/wp-content/uploads/2017/03/beef-souvlaki-skewers-107.jpg",
               description: "This Greek Beef souvlaki recipe (skewers) takes you back to your favourite Taverna! Complete with best chicken souvlaki marinade and what to serve along.",
               ingredients: "4 boneless chicken breasts (approx. 1 kg/35 ounces),4 tbsps olive oil,juice of 1 lemon,1 clove of garlic, minced,2 tbsp dried oregano,salt and freshly ground pepper,1 cucumber,2 cloves of garlic, minced,1/4 of a cup extra virgin olive oil,500g of strained yogurt (18 ounces),1–2 tbsps of red wine vinegar,a pinch of salt,8 pita breads,olive oil,1–2 tsps dried oregano,1 tomato sliced,1 red onion sliced,fried potatoes (optional),romaine (cos) lettuce (optional),salt and freshly ground pepper,8–9 wooden skewers",
               directions: "To prepare this chicken souvlaki recipe, start by preparing the marinade. Cut the chicken breasts into 2-3 cm pieces and place them in a large bowl, along with all the marinade ingredients. Use your hands to mix really well, cover with plastic wrap and put in the fridge for 30-60 minutes. In the meantime prepare the tzatziki sauce for the chicken souvlaki. Pour in a blender the olive oil and grated garlic and blend until combined. Remove the skin and the seeds of the cucumber and grate it into a large bowl. Season with salt and pepper and leave aside for 10 minutes. Wrap the grated cucumber in a towel and squeeze, in order to get rid of the excess water. In a bowl, add the cucumber, the blended garlic and oil, the yogurt, 1-2 tbsps of red wine vinegar, a pinch of salt and blend, until the ingredients are combined. Store the tzatziki sauce in the fridge and always serve cold. To assemble the chicken souvlaki (skewers), cut the wooden skewers to fit your griddle pan and soak them in water. (This will prevent them from burning.) Thread the chicken pieces, comfortably, on the skewers. Preheat a grill or griddle pan on a high heat. Cook the chicken souvlaki (skewers) for about 8 to 10 minutes, turning occasionally, until nicely coloured on all sides and cooked through. While your chicken souvlaki is cooking, prepare the pita breads. Preheat the oven to 250C. Use a cooking brush to oil the pita breads on both sides and season with salt and oregano. Place a large oven tray (upside down) at the bottom of the oven and place the pita breads on top of the tray. Bake for 2 minutes. (Alternatively you can use a griddle pan or a grill.) To serve the chicken souvlaki (skewers), slice 2 red onions and place on a platter; top with the chicken souvlaki (skewers), drizzle with some extra virgin olive oil and a good squeeze of lemon juice. Serve while still warm with some pita breads and tzatziki sauce. You can also serve the chicken souvlaki (skewers) wrapped, like a sandwich. Spread some tzatziki sauce on the pita breads and top it with the chicken souvlaki (skewers), sliced onions, tomatoes and fried potatoes and wrap. Enjoy!",
               category: "Dinner",
               cuisine: "Greek",
               datePublished: "2014-05-26",
               url: "https://www.mygreekdish.com/recipe/souvlaki-with-chicken-and-pita-breads/")
    ]
}
